language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/symfony-bridge/.phpunit
php:
  - '7.3'
  - '7.4'

APP_ENV:
  - test
  
install:
  - composer install

script:
  - php bin/phpunit
