language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/symfony-bridge/.phpunit
php:
  - '7.3'
  - '7.4'

env:
  - SYMFONY_VERSION="test" DB=sqlite

install:
  - composer install

script:
  - php bin/phpunit
